### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by london111** [avian2/pylog2rotate#1]
I have a backup script which produces (using rsync and hardlinks) a backupdirectory rsync_backup like this:

ls rsync_backup | tail
back-2015-01-28T20_16_22
back-2015-02-20T21_11_19
back-2015-02-21T22_07_11
back-2015-02-23T21_35_11
back-2015-02-25T21_03_26
back-2015-04-20T22_33_26
back-2015-04-22T21_36_43
back-2015-04-23T21_29_45
back-2015-04-29T21_07_46

How can I use your pylog2rotate tool in this case?

Is it possible just to show what would be done?

**Comment by avian2** [comment]
In your case you can get a list of backup directories to keep with a command like this:

`ls rsync_backup | log2rotate -k -f back-%Y-%m-%dT%H_%M_%S`

Change `-k` to `-d` to get a list of directories to delete instead. It's up to you to write a shell script that actually deletes the directories.
